### ISSUE TITLE
what numpy version and PETSC_ARCH should I take?

### ISSUE THREAD

**Issue by bernardyeszero** [josh146/pyctqw#1]
Hi, I'm trying to install pyCTQW package via pip, and now I have a problem, the error information is:

**Error: Element in COMPLEX(8) array constructor at (1) is REAL(8)**

My system is Ubuntu 14.04, and I use petsc-3.4.5, slepc-3.4.4, openmpi-1.8.4, petsc4py-3.4. And I put them into the same path and when run ./configure, I add the prefix like /usr/local/PACKAGE_NAME.

I think the error maybe caused by error numpy version(I've tried the 1.6.0, 1.8.2 and so on) or the error PETSC_ARCH(I've tried linux-complex and linux-gnu).

Could you please give me some advice to install the package successfully? Thank you very much for your kind attention.

**Comment by josh146** [comment]
The error message you are getting seems to imply that the PETSc/SLEPc version you are using has been compiled to use real numbers only. Unfortunately, this is an issue with the Ubuntu repository versions of PETSc and SLEPc, which do not allow complex numbers; a big issue if trying to do some quantum calculations!

In order to get around this, you may have to compile PETSc and SLEPc from source yourself (I am unaware of any Ubuntu packages which have complex numbers enabled). When compiling PETSc, make sure to use the flag:

`--with-scalar-type=complex`

Then, when compiling SLEPc, petsc4py, and pyCTQW, make sure to point them to the locally compiled PETSc installation with complex numbers enabled using the correct `PETSC_DIR` environment variable.

Hope this helps, let me know if you run into any other issues.

**Comment by bernardyeszero** [comment]
Wow! Thank you very much for your suggestion. It does work!!! Additionally, I change the PETSC_ARCH from linux-gnu to linux-complex. Thanks!
